-- FoodCheck Egypt optional Supabase schema
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  code text not null,
  name text not null,
  brands text,
  ingredients_text text,
  nutriments jsonb not null default '{}'::jsonb,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists products_code_unique on public.products(code);

alter table public.products enable row level security;

drop policy if exists "Public can read approved products" on public.products;
create policy "Public can read approved products"
on public.products for select
using (status = 'approved');

drop policy if exists "Public can submit pending products" on public.products;
create policy "Public can submit pending products"
on public.products for insert
with check (status = 'pending');

-- Do not add public UPDATE/DELETE policies.
-- Review/approval should be performed by a trusted admin path, never with a service-role key in the browser.
